import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
test('calibration packet stays compact, versioned, and available from the Pages lab', async () => {
  const packet = await readFile('src/worldgen/calibrationPacket.ts', 'utf8');
  const controller = await readFile('src/worldgen/diagnostics/worldgenClimateLabStandalone.ts', 'utf8');
  const html = await readFile('index.html', 'utf8');
  assert.match(packet, /planet-engine-calibration@1/);
  assert.match(packet, /RANKED_LIMIT = 8/);
  assert.match(packet, /crust_freeboard/);
  assert.match(packet, /mean_subsidence_history/);
  assert.match(packet, /mean_basin_potential/);
  assert.match(packet, /mean_crust_density_kg_per_m3/);
  assert.match(packet, /restored_margin_material_fraction_of_continental/);
  assert.match(packet, /historical_identity/);
  assert.match(packet, /surface_water_mass_kg/);
  assert.match(packet, /water_volume_relative_error/);
  assert.doesNotMatch(packet, /JSON\.stringify\(result/);
  assert.match(controller, /worldCalibrationMarkdown/);
  assert.match(controller, /worldCalibrationJson/);
  assert.match(controller, /worldgen-copy-calibration/);
  assert.match(controller, /worldgen-download-calibration/);
  assert.match(html, /Copy LLM Summary/);
  assert.match(html, /Download Calibration JSON/);
});
